language: java
sudo: false
script: mvn clean verify

deploy:
  provider: releases
  api_key: $TOKEN
  file_glob: true
  file: "target/*.jar"
  skip_cleanup: true
  on:
    branches:
      only:
        - develop
