language: java
install: true
script:
- mvn install
jdk:
  - oraclejdk8
sudo: false
script: mvn clean verify assembly:single
notifications:
  email:
    recipients:
        rakdominikrak@gmail.com
        mkopka97@gmail.com
        pawo97@o2.pl
    on_success: never
    on_failure: always
before_deploy:
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: GIT_AUTH
  file: "target/*.jar"
  skip_cleanup: true
  on:
    repo: IIS-ZPI/ZPI_2019_Dzienni_IO2_1
    branches:
      only:
        - master
